name: FrameComp
options:
  bundleIdPrefix: com.framecomp
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.0"
targets:
  FrameComp:
    type: application
    platform: iOS
    sources:
      - path: FrameComp
        excludes: ["**/framecomp_spec.txt"]
    settings:
      base:
        INFOPLIST_FILE: FrameComp/App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
